apiVersion: v1
kind: Service
metadata:
  name: capstone-app
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 31234
      name: tcp-5000
      protocol: TCP
  selector:
    app: capstone-app
