apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: eu-west-1

vpc:
  id: "vpc-08724b020f1a7ce7a"
  cidr: "10.0.0.0/16"
  subnets:
    private:
      us-west-2a:
          id: "subnet-0599fc3612eb2bc18"
          cidr: "10.0.0.0/24"
      us-west-2b:
          id: "subnet-02ba1614cd1111fd2"
          cidr: "10.0.1.0/24"
      us-west-2c:
          id: "subnet-09a033b18ab769a47"
          cidr: "10.0.2.0/24"

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    minSize: 2
    maxSize: 3
